# Simulating intelligence


The overall goal is to create a learning system that learns with no indication of the outcome. No target output and no reward function. Just unstructured data and trying to categorize it. I am borrowing ideas from long term potentiation and long term depression in neurons in learning.

I am hoping to find that there is a natural categorization of two different types of input using natural phenomenons in biology

## 1. create the input

In [2]:
import numpy as np

# Create a 4x4 matrix with 1s and 0s
matrix = np.array([[1, 0, 0, 0],
                   [1, 0, 0, 0],
                   [1, 0, 0, 0],
                   [1, 0, 0, 0]])

print(matrix)

[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]


## create 2x2 filter

In [3]:
import numpy as np

# Create a 2x2 filter with random numbers
filter_matrix = np.random.rand(2, 2)

print(filter_matrix)


[[0.76724872 0.49596287]
 [0.25436204 0.9674283 ]]


these are the weights